// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQFA9nPXa9RpI8rwbn1ZchJQOxl6sfm0',
    appId: '1:962805598055:web:972bc7e019801631fed1c2',
    messagingSenderId: '962805598055',
    projectId: 'fluttergram-5040c',
    authDomain: 'fluttergram-5040c.firebaseapp.com',
    storageBucket: 'fluttergram-5040c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohCP4X6UdTnLD1M1qUdwKINoQjx4Wxrk',
    appId: '1:962805598055:android:375cde1104e818fbfed1c2',
    messagingSenderId: '962805598055',
    projectId: 'fluttergram-5040c',
    storageBucket: 'fluttergram-5040c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOhLPsD_4fq7U2JLBlsNPL82VGUcMz-8',
    appId: '1:962805598055:ios:ae4262d535f148e3fed1c2',
    messagingSenderId: '962805598055',
    projectId: 'fluttergram-5040c',
    storageBucket: 'fluttergram-5040c.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOhLPsD_4fq7U2JLBlsNPL82VGUcMz-8',
    appId: '1:962805598055:ios:f0ab2bfd1aab87d4fed1c2',
    messagingSenderId: '962805598055',
    projectId: 'fluttergram-5040c',
    storageBucket: 'fluttergram-5040c.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
