import Link from 'next/link'
import './globals.css'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './LogoutBtn'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en"> 
      <body>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          <Link href="/write">Write</Link>
          {
            session ? <span>{session.user.name} <LogoutBtn></LogoutBtn></span> : <LoginBtn></LoginBtn>
          }
        </div> 
        {children}
      </body>
    </html>
  )
}
